# Mikrofon ayarları
NOTE_DURATION = 2
SAMPLE_RATE = 44100
ACCEPTABLE_MARGIN = 40

# Test parametreleri
MAX_ATTEMPTS = 2
MIN_SUCCESS_RATE = 80

# Görselleştirme ayarları
VISUALIZATION_WIDTH = 100
TOTAL_MIN_FREQ = 80
TOTAL_MAX_FREQ = 550 